# Generated by Django 3.1.7 on 2021-03-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='deposit_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=150),
        ),
        migrations.DeleteModel(
            name='DepositMethod',
        ),
    ]
