# Generated by Django 3.1.7 on 2021-03-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_auto_20210318_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposits',
            name='is_business',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='is_personal',
        ),
        migrations.AddField(
            model_name='deposits',
            name='account_no',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='deposits',
            name='branch',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='deposits',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deposits',
            name='purpose',
            field=models.CharField(choices=[('Business', 'Business'), ('Personal', 'Personal')], default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='deposits',
            name='source_of_deposit',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online'), ('Remittance', 'Remittance'), ('Ime', 'Ime')], max_length=150),
        ),
    ]
