# Generated by Django 3.1.7 on 2021-03-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_auto_20210318_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
