# Generated by Django 3.1.7 on 2021-03-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_deposits_cheque_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='cheque_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cheque_images/'),
        ),
    ]
