# Generated by Django 3.1.7 on 2021-03-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0005_deposits_cheque_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='deposit_slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/deposit_slip'),
        ),
    ]
