# Generated by Django 3.1.7 on 2021-03-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0006_deposits_deposit_slip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='account_no',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
