# Generated by Django 3.1.7 on 2021-04-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0007_auto_20210319_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='purpose',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business')], max_length=200),
        ),
    ]
