# Generated by Django 3.1.7 on 2021-04-04 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposit', '0008_auto_20210404_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('expense_type', models.CharField(choices=[('Cost of goods sold', 'Cost of goods sold'), ('Selling and distribution expenses', 'Selling and distribution expenses'), ('Operating, general and administrative expenses', 'Operating, general and administrative expenses'), ('Salaries, wages, and benefits', 'Salaries, wages, and benefits'), ('Rent expense', 'Rent expense'), ('Cost of utilities', 'Cost of utilities'), ('Provisions and impairments', 'Provisions and impairments'), ('Depreciation expense', 'Depreciation expense'), ('Amortization expense', 'Amortization expense'), ('Printing and stationery expense', 'Printing and stationery expense'), ('Staff traveling expense', 'Staff traveling expense'), ('Repair and maintenance expense', 'Repair and maintenance expense'), ('Insurance cost', 'Insurance cost'), ('Legal and professional charges', 'Legal and professional charges'), ('Communication expense', 'Communication expense'), ('Miscellaneous expenses', 'Miscellaneous expenses'), ('Finance cost', 'Finance cost'), ('Taxation', 'Taxation')], max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit', 'Credit'), ('E-Payment', 'E-Payment')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('expense_sub_category', models.CharField(max_length=300)),
                ('invoice_number', models.CharField(max_length=300)),
                ('invoice_image', models.ImageField(blank=True, null=True, upload_to='images/invoice_images/')),
                ('amount', models.PositiveIntegerField()),
                ('cheque_no', models.CharField(blank=True, max_length=200, null=True)),
                ('cheque_image', models.ImageField(blank=True, null=True, upload_to='images/cheque_images/')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expensetype')),
                ('payment_made_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit.persondetail')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.paymenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
