# Generated by Django 3.1.7 on 2021-04-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='expense_type',
            field=models.CharField(choices=[('Cost of goods sold', 'Cost of goods sold'), ('Selling and distribution expenses', 'Selling and distribution expenses'), ('Operating, general and administrative expenses', 'Operating, general and administrative expenses'), ('Salaries, wages, and benefits', 'Salaries, wages, and benefits'), ('Rent expense', 'Rent expense'), ('Cost of utilities', 'Cost of utilities'), ('Provisions and impairments', 'Provisions and impairments'), ('Depreciation expense', 'Depreciation expense'), ('Amortization expense', 'Amortization expense'), ('Printing and stationery expense', 'Printing and stationery expense'), ('Staff traveling expense', 'Staff traveling expense'), ('Repair and maintenance expense', 'Repair and maintenance expense'), ('Insurance cost', 'Insurance cost'), ('Legal and professional charges', 'Legal and professional charges'), ('Communication expense', 'Communication expense'), ('Miscellaneous expenses', 'Miscellaneous expenses'), ('Finance cost', 'Finance cost'), ('Taxation', 'Taxation')], default='Cost of goods sold', max_length=300),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit', 'Credit'), ('E-Payment', 'E-Payment')], default='Cash', max_length=200),
        ),
    ]
