# Generated by Django 3.1.7 on 2021-04-06 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_contact_contacttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.contact'),
        ),
    ]
