# Generated by Django 3.1.6 on 2021-03-18 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('deposit', '0003_auto_20210318_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('withdraw_date', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('withdraw_method', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online'), ('Remittance', 'Remittance'), ('Ime', 'Ime')], max_length=150)),
                ('purpose', models.CharField(choices=[('Business', 'Business'), ('Personal', 'Personal')], default='1', max_length=200)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit.persondetail')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.institutiondetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
