# Generated by Django 3.1.7 on 2021-03-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_method',
            field=models.CharField(choices=[('ATM', 'ATM'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=150),
        ),
    ]
