# Generated by Django 3.1.7 on 2021-03-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0002_auto_20210318_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='source',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='what_purpose',
            field=models.CharField(default='', max_length=250),
        ),
    ]
