# Generated by Django 3.1.7 on 2021-03-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0003_auto_20210318_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='what_purpose',
            field=models.CharField(default='1', max_length=250),
        ),
    ]
