# Generated by Django 3.1.7 on 2021-04-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0004_auto_20210319_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='purpose',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business')], default='1', max_length=200),
        ),
    ]
